import * as fs from 'fs';
import * as path from 'path';

/**
 * Metadata Entity to Spring Boot JPA Entity Generator
 * Reads JSON schema from /metadata/entities/ and renders Java Entity class.
 */
export function generateJpaEntity(schemaPath: string, outputDir: string): void {
  const rawData = fs.readFileSync(schemaPath, 'utf-8');
  const schema = JSON.parse(rawData);

  const className = schema.entityName.charAt(0).toUpperCase() + schema.entityName.slice(1);
  const tableName = schema.tableName || schema.entityName.toLowerCase();
  const schemaName = schema.schemaName || 'domain';

  const javaCode = `package health.hemp.domain.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * ${schema.displayName || className}
 * Auto-generated by Code Generation Framework from ${schema.entityId || 'metadata'}
 */
@Entity
@Table(name = "${tableName}", schema = "${schemaName}")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ${className}Entity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = OffsetDateTime.now();
    }
}
`;

  const outputPath = path.join(outputDir, `${className}Entity.java`);
  fs.writeFileSync(outputPath, javaCode, 'utf-8');
  console.log(`Generated JPA Entity: ${outputPath}`);
}
